name: "Mirror doc/ to wiki"

# Run on changes to the `doc` directory on the `master` branch
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
        
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Generate documentation
        run: npm run generate-doc

      - name: Checkout main
        uses: actions/checkout@v2

      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: "[owner]/[repo name].wiki"
          path: [repo name].wiki
      - name: Copy files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Wiki mirror"
          cp $GITHUB_WORKSPACE/[repo name]/doc/*.txt $GITHUB_WORKSPACE/[repo name].wiki
          cd $GITHUB_WORKSPACE/[repo name].wiki
          rename.ul -v .txt .md *.txt
          git add .
          # only commit if there are changes
          git diff-index --quiet HEAD -- || git commit -m "sync from doc/"
          git push